module.exports = {
  id: 'logo_recognition_visual',
  viewports: [
    { label: 'phone', width: 320, height: 480 },
    { label: 'tablet', width: 1024, height: 768 },
    { label: 'desktop', width: 1920, height: 1080 },
    { label: '4k', width: 3840, height: 2160 },
  ],
  onBeforeScript: 'puppet/onBefore.js',
  onReadyScript: 'puppet/onReady.js',
  scenarios: [
    {
      label: 'Homepage',
      url: 'http://localhost:3000',
      selectors: ['document'],
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
    },
    {
      label: 'Recognition Interface',
      url: 'http://localhost:3000/recognize',
      selectors: ['document', '.upload-area', '.results-display'],
      misMatchThreshold: 0.1,
      delay: 500,
    },
    {
      label: 'Dark Mode',
      url: 'http://localhost:3000',
      clickSelector: '[data-testid="theme-toggle"]',
      selectors: ['document'],
      misMatchThreshold: 0.2,
    },
    {
      label: 'Mobile Menu',
      url: 'http://localhost:3000',
      viewports: [{ label: 'phone', width: 320, height: 480 }],
      clickSelector: '[data-testid="mobile-menu-toggle"]',
      selectors: ['document'],
      misMatchThreshold: 0.1,
    },
  ],
  paths: {
    bitmaps_reference: 'tests/visual/reference',
    bitmaps_test: 'tests/visual/test',
    engine_scripts: 'tests/visual/engine_scripts',
    html_report: 'tests/visual/report',
    ci_report: 'tests/visual/ci',
  },
  report: ['browser', 'CI'],
  engine: 'playwright',
  engineOptions: {
    browser: 'chromium',
    args: ['--no-sandbox'],
  },
  asyncCaptureLimit: 5,
  asyncCompareLimit: 50,
  debug: false,
  debugWindow: false,
};
